### ISSUE TITLE
How to validate that user has certain metadata?

### ISSUE THREAD

**Issue by hannupekka** [auth0/express-jwt#108]
As an example, two Express routes:
`GET /user`
`GET /admin`

My users have following metadata:
```javascript
user_metadata: {
  roles: ['admin'] // or 'user'
}
``` 

Is it possible to validate, that `GET /user` can be accessed by those who have role `user` and `GET /admin` by those who have role `admin`?

Currenly on route handler after using `jwt` my `req.user` does not have any of users metadata, only following properties:
```javascript
 {
    iss: 'https://myapp.eu.auth0.com/',
    sub: 'auth0|foobar...',
    aud: 'audience',
    exp: 1452058228,
    iat: 1452022228
}
```

**Comment by sandrinodimattia** [comment]
I think it would be better to ask this question on https://ask.auth0.com as it is more related to Auth0 than to express-jwt.

But for this to work correctly, your token needs to contain the information (eg: roles). In order to do so with Auth0, you have to request the appropriate scope, eg: `scope=openid email roles`. The scope can be specified in auth0.js, in the Lock, in the `/authorize` and `/ro` endpoints, ...

**Comment by hannupekka** [comment]
@sandrinodimattia thank you very much! :)

**Comment by razvanilin** [comment]
Hi @hannupekka , I am looking for ways to do this too. Have you found a way to do it?

**Comment by yageek** [comment]
For any developer that arrives here, the solution is explained here: https://auth0.com/forum/t/user-metadata-or-app-metadata-in-jwt/3117
