### ISSUE TITLE
Not to ask Bearer?

### ISSUE THREAD

**Issue by iamdubx** [auth0/express-jwt#177]
Hi. How to make express-jwt not to demand 'Bearer' in token? I have clients that doesn't set it, and it is fairly consuming to rewrite it.

**Comment by iamdubx** [comment]
I reopen this, since I can't handle this error `Format is Authorization: Bearer [token]`

How to turn of Bearer???

**Comment by iamdubx** [comment]
Ohh, sorry, I fixed it

**Comment by brenwell** [comment]
Hey guys Is there a way to squash this warning?

I want to put `express-jwt` in front of all my routes because I am using just one `/graphql`

And originally the client has no token thus not sending it and then after authentication it it sends it every request.

I had assumed `credentialsRequired: false` would do the trick, but alas

Any way thanks for the cool lib nonetheless

**Comment by brenwell** [comment]
I see that the issue is I can't send

* `Authorization:`
* `Authorization: Bearer`
* `Authorization: Bearer sOmeCrAp`

The header must be missing completely

I was sending `Authorization:`

Thanks anway guys
