### ISSUE TITLE
Usage with Passport?

### ISSUE THREAD

**Issue by breandr** [auth0/express-jwt#49]
I want to use Passport for it's social strategies, and I want to use express-jwt for email/password JWT authentication, but I have not been able to find any examples of integrating the two. Is there a way to integrate the two? Or is it completely absurd to use them both?

**Comment by MichielDeMey** [comment]
Take a look at this SO question:
http://stackoverflow.com/questions/20228572/passport-local-with-node-jwt-simple

**Comment by jfromaniello** [comment]
Yes, as in the link that @MichielDeMey shared to stackoverflow, you might use node-jsonwebtoken with passport-local, instead of express-jwt.

Before starting this project we considered doing a passport-jwt instead but in the end we though it wasn't that useful, we didn't have any use case as yours where you need some passport strategy + jwt.
