### ISSUE TITLE
Does express-jwt support asymmetric encryption?

### ISSUE THREAD

**Issue by jedd-ahyoung** [auth0/express-jwt#87]
I'm looking for a method of using asymmetric encryption with JWT. From what I can see, the auth0 libraries don't seem to support setting an encryption type. Is this possible?

**Comment by eugeniop** [comment]
Yes, it does support asymmetric algorithms. See here: https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback

**Comment by jedd-ahyoung** [comment]
Yeah, whoops. I saw that later and was wondering how you would set the
algorithm type - then I remembered, I'm using JSONWebToken to sign and
create the JWTs; express-jwt is only responsible for the middleware
portion. I think I can work from this point.

**Comment by jfromaniello** [comment]
@jedd-ahyoung neither of these libraries support encryption, the token payload is not encrypted just base64-url encoded and digital signed.

These algs are for SIGNING the tokens not encrypting.

It is worth mentioning that express-jwt uses jsonwebtoken and there are two options when validating token signatures:

1.  *implicit*: depending on the type of secret you specify we allow certain algs. If your secret starts with -`---BEGIN CERT` we allow tokens signed with an asymmetric key.
2. *explicit*: you can pass to express-jwt an alghortims option as follows:

```javascript
app.use(expressJWT({ secret: theKey, algorithms: [ 'RS256','RS384','RS512' ] } );
```

This is because the header in the token is not enough, and there used to be a vulnerability where an attacker could sign a token with a public key but use the alg: symm. [more info](https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/)

**Comment by jedd-ahyoung** [comment]
As express-jwt supports asymmetric keys - does it support asymmetric keys in other formats besides PEM? Just curious.

**Comment by jfromaniello** [comment]
@jedd-ahyoung sorry for the delay, the answer is no
